apiVersion: v1
kind: ConfigMap
metadata:
  name: usersapi-config
  namespace: usersapi
data:
  RabbitMQ__Host: rabbitmq
  RabbitMQ__Username: rabbitmq
  Jwt__Issuer: "UsersAPI"
  Jwt__Audience: "UsersAPI"