apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  namespace: notifications
data:
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_USERNAME: guest
  QUEUE_USER_CREATED: Shared.Contracts.Events:UserCreatedIntegrationEvent
  QUEUE_PAYMENT_PROCESSED: Shared.Contracts.Events:PaymentProcessedEvent